server:
  port: 9090
  servlet:
    context-path: /api
spring:
  application:
    name: bluex
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
      write-dates-as-timestamps: false
    #设置空如何序列化
    defaultPropertyInclusion: ALWAYS
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
  datasource:
    url: jdbc:oracle:thin:@10.100.3.238:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: sw_ori
    password: sw
mybatis-plus:
  mapper-locations: classpath*:/com/zsb/model/bluex/**/*.xml
bluex:
  enum-scan-paths:
    - com.zsb.bluex.defaults.enums
  type-scan-paths:
    - com.zsb.bluex.defaults.types
  function-scan-paths:
    - com.zsb.bluex.defaults.libs